# version: '3.6'

services:
  db:
    image: mysql:5.7 
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: 'sql_db' 
      MYSQL_USER: 'irul'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - LK2
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'secret'
    networks:
      - LK2
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - db
      - phpmyadmin
    volumes:
      - ./nginx.conf:/etc/nginx.conf
    networks:
      - LK2

networks:
  LK2: {}

volumes:
  mysql_db: {}
